language: node_js
sudo: false
node_js:
  - "5"
env:
  global:
    - BIN="node" ISTANBUL=false OPTION=""
    - NPM_VERSION="^2.0.0" SAUCE_LABS=false SAUCE_USERNAME="lodash"
    - PATTERN1="s|\s*if\s*\(isHostObject\b[\s\S]+?\}(?=\n)||"
    - PATTERN2="s|\s*if\s*\(enumerate\b[\s\S]+?\};\s*\}||"
    - PATTERN3="s|\s*while\s*\([^)]+\)\s*\{\s*iteratee\(index\);\s*\}||"
    - secure: "tg1JFsIFnxzLaTboFPOnm+aJCuMm5+JdhLlESlqg9x3fwro++7KCnwHKLNovhchaPe4otC43ZMB/nfWhDnDm11dKbm/V6HlTkED+dadTsaLxVDg6J+7yK41QhokBPJOxLV78iDaNaAQVYEirAgZ0yn8kFubxmNKV+bpCGQNc9yU="
  matrix:
    -
    - BIN="phantomjs"
    - ISTANBUL=true
    - SAUCE_LABS=true
matrix:
  include:
    - node_js: "0.8"
      env: NPM_VERSION="~1.4.0"
    - node_js: "0.10"
      env:
    - node_js: "0.12"
      env:
    - node_js: "4"
      env:
git:
  depth: 10
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4aab6358b0e9aed0b628
    on_success: change
    on_failure: always
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm config set loglevel error"
  - "npm i -g npm@\"$NPM_VERSION\""
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli ./node_modules/lodash-cli && mkdir $_/node_modules && cd $_ && ln -s ../../../ ./lodash && cd ../ && npm i && cd ../../"
  - "node ./node_modules/lodash-cli/bin/lodash -o ./lodash.js"
  - "[ $ISTANBUL == false ]   || perl -0pi -e \"$PATTERN1\" ./lodash.js"
  - "[ $ISTANBUL == false ]   || perl -0pi -e \"$PATTERN2\" ./lodash.js"
  - "[ $ISTANBUL == false ]   || perl -0pi -e \"$PATTERN3\" ./lodash.js"
script:
  - "[ $ISTANBUL == false ]   || node ./node_modules/istanbul/lib/cli.js cover -x \"**/vendor/**\" --report lcovonly ./test/test.js -- ./lodash.js"
  - "[ $ISTANBUL == false ]   || [ $TRAVIS_SECURE_ENV_VARS == false ] || (cat ./coverage/lcov.info | coveralls) || true"
  - "[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || cd ./test"
  - "[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || $BIN $OPTION ./test.js ../lodash.js"
  - "[ $SAUCE_LABS == true ]  || [ $ISTANBUL == true ] || [ $TRAVIS_SECURE_ENV_VARS == false ] || $BIN $OPTION ./test.js ../lodash.min.js"
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"lodash tests\"     runner=\"test/index.html?build=../lodash.js&noglobals=true\"     tags=\"development\""
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"lodash tests\"     runner=\"test/index.html?build=../lodash.min.js&noglobals=true\" tags=\"production\""
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"underscore tests\" runner=\"test/underscore.html?build=../lodash.js\"               tags=\"development,underscore\""
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"underscore tests\" runner=\"test/underscore.html?build=../lodash.min.js\"           tags=\"production,underscore\""
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"backbone tests\"   runner=\"test/backbone.html?build=../lodash.js\"                 tags=\"development,backbone\""
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"backbone tests\"   runner=\"test/backbone.html?build=../lodash.min.js\"             tags=\"production,backbone\""
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"backbone tests\"   runner=\"test/backbone.html?build=../dist/lodash.core.js\"       tags=\"development,backbone\""
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"backbone tests\"   runner=\"test/backbone.html?build=../dist/lodash.core.min.js\"   tags=\"production,backbone\""
